### ISSUE TITLE
Source code formatting showing up in Add Goal options

### ISSUE THREAD

**Issue by dfirsht** [IBM-MIL/IBM-Ready-App-for-Banking#8] opened 2015-10-12 19:37 UTC
Steps to reproduce: Add goal > More Options > this screen
![img_0032](https://cloud.githubusercontent.com/assets/5191832/10436855/c4b6a48a-70ee-11e5-8bc8-3fb3d6c620cc.PNG)

**Comment by sccheng** [comment] 2015-11-04 17:33
Closing this issue, since we are unable to reproduce it.

**Closed** 2015-11-04 17:33 UTC
Labels: bug
